services:
  postgres:
    image: postgres:15
    container_name: user-management-db
    restart: always
    environment:
      POSTGRES_DB: user_management
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
